// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHNOROaQHDYc6oQSnyaHizmEMDdvhUXVc',
    appId: '1:308192094271:web:417d5ecccdda4f0a66b08a',
    messagingSenderId: '308192094271',
    projectId: 'doctonear-b270e',
    authDomain: 'doctonear-b270e.firebaseapp.com',
    storageBucket: 'doctonear-b270e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1pcrsGpORQoJql2iO7Voq3UE0ONFwvV0',
    appId: '1:308192094271:android:35d5cc2d3b8acbff66b08a',
    messagingSenderId: '308192094271',
    projectId: 'doctonear-b270e',
    storageBucket: 'doctonear-b270e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tDCvIGPPxS95K_-qprKJ6Tt-as1lS7k',
    appId: '1:308192094271:ios:04ba4e5ef58150bd66b08a',
    messagingSenderId: '308192094271',
    projectId: 'doctonear-b270e',
    storageBucket: 'doctonear-b270e.firebasestorage.app',
    iosBundleId: 'com.example.medichub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1tDCvIGPPxS95K_-qprKJ6Tt-as1lS7k',
    appId: '1:308192094271:ios:04ba4e5ef58150bd66b08a',
    messagingSenderId: '308192094271',
    projectId: 'doctonear-b270e',
    storageBucket: 'doctonear-b270e.firebasestorage.app',
    iosBundleId: 'com.example.medichub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHNOROaQHDYc6oQSnyaHizmEMDdvhUXVc',
    appId: '1:308192094271:web:14246e64d854294d66b08a',
    messagingSenderId: '308192094271',
    projectId: 'doctonear-b270e',
    authDomain: 'doctonear-b270e.firebaseapp.com',
    storageBucket: 'doctonear-b270e.firebasestorage.app',
  );
}
